name: Pull Request
on: [pull_request]

jobs:
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: checkout source
        uses: actions/checkout@v2

      - name: build
        run: go build -tags 'containers_image_openpgp' -o sinker main.go

      - name: lint go
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.46.2
          ./bin/golangci-lint run --build-tags='containers_image_openpgp' --timeout=5m --color=always --max-same-issues=0 --max-issues-per-linter=0

      - name: unit tests
        run: make test
